// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PACKETSELECTTEAM_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETSELECTTEAM_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

namespace packets {

struct PacketSelectTeam;

struct PacketSelectTeam FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_TEAM = 6
  };
  uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
  int16_t team() const { return GetField<int16_t>(VT_TEAM, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           VerifyField<int16_t>(verifier, VT_TEAM) &&
           verifier.EndTable();
  }
};

struct PacketSelectTeamBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) { fbb_.AddElement<uint32_t>(PacketSelectTeam::VT_ID, id, 0); }
  void add_team(int16_t team) { fbb_.AddElement<int16_t>(PacketSelectTeam::VT_TEAM, team, 0); }
  PacketSelectTeamBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PacketSelectTeamBuilder &operator=(const PacketSelectTeamBuilder &);
  flatbuffers::Offset<PacketSelectTeam> Finish() {
    auto o = flatbuffers::Offset<PacketSelectTeam>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<PacketSelectTeam> CreatePacketSelectTeam(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t id = 0,
   int16_t team = 0) {
  PacketSelectTeamBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_team(team);
  return builder_.Finish();
}

inline const packets::PacketSelectTeam *GetPacketSelectTeam(const void *buf) { return flatbuffers::GetRoot<packets::PacketSelectTeam>(buf); }

inline bool VerifyPacketSelectTeamBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<packets::PacketSelectTeam>(); }

inline void FinishPacketSelectTeamBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<packets::PacketSelectTeam> root) { fbb.Finish(root); }

}  // namespace packets

#endif  // FLATBUFFERS_GENERATED_PACKETSELECTTEAM_PACKETS_H_
