// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PACKETDELETECHARACTER_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETDELETECHARACTER_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

namespace packets {

struct PacketDeleteCharacter;

struct PacketDeleteCharacter FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4
  };
  uint32_t id() const { return GetField<uint32_t>(VT_ID, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID) &&
           verifier.EndTable();
  }
};

struct PacketDeleteCharacterBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) { fbb_.AddElement<uint32_t>(PacketDeleteCharacter::VT_ID, id, 0); }
  PacketDeleteCharacterBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PacketDeleteCharacterBuilder &operator=(const PacketDeleteCharacterBuilder &);
  flatbuffers::Offset<PacketDeleteCharacter> Finish() {
    auto o = flatbuffers::Offset<PacketDeleteCharacter>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<PacketDeleteCharacter> CreatePacketDeleteCharacter(flatbuffers::FlatBufferBuilder &_fbb,
   uint32_t id = 0) {
  PacketDeleteCharacterBuilder builder_(_fbb);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const packets::PacketDeleteCharacter *GetPacketDeleteCharacter(const void *buf) { return flatbuffers::GetRoot<packets::PacketDeleteCharacter>(buf); }

inline bool VerifyPacketDeleteCharacterBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<packets::PacketDeleteCharacter>(); }

inline void FinishPacketDeleteCharacterBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<packets::PacketDeleteCharacter> root) { fbb.Finish(root); }

}  // namespace packets

#endif  // FLATBUFFERS_GENERATED_PACKETDELETECHARACTER_PACKETS_H_
