// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_PACKETCLIENTSELECTEDTEAM_PACKETS_H_
#define FLATBUFFERS_GENERATED_PACKETCLIENTSELECTEDTEAM_PACKETS_H_

#include "flatbuffers/flatbuffers.h"

namespace packets {

struct PacketClientSelectedTeam;

struct PacketClientSelectedTeam FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_SLOT = 4,
    VT_TEAM = 6
  };
  int16_t slot() const { return GetField<int16_t>(VT_SLOT, 0); }
  int16_t team() const { return GetField<int16_t>(VT_TEAM, 0); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_SLOT) &&
           VerifyField<int16_t>(verifier, VT_TEAM) &&
           verifier.EndTable();
  }
};

struct PacketClientSelectedTeamBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_slot(int16_t slot) { fbb_.AddElement<int16_t>(PacketClientSelectedTeam::VT_SLOT, slot, 0); }
  void add_team(int16_t team) { fbb_.AddElement<int16_t>(PacketClientSelectedTeam::VT_TEAM, team, 0); }
  PacketClientSelectedTeamBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  PacketClientSelectedTeamBuilder &operator=(const PacketClientSelectedTeamBuilder &);
  flatbuffers::Offset<PacketClientSelectedTeam> Finish() {
    auto o = flatbuffers::Offset<PacketClientSelectedTeam>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<PacketClientSelectedTeam> CreatePacketClientSelectedTeam(flatbuffers::FlatBufferBuilder &_fbb,
   int16_t slot = 0,
   int16_t team = 0) {
  PacketClientSelectedTeamBuilder builder_(_fbb);
  builder_.add_team(team);
  builder_.add_slot(slot);
  return builder_.Finish();
}

inline const packets::PacketClientSelectedTeam *GetPacketClientSelectedTeam(const void *buf) { return flatbuffers::GetRoot<packets::PacketClientSelectedTeam>(buf); }

inline bool VerifyPacketClientSelectedTeamBuffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<packets::PacketClientSelectedTeam>(); }

inline void FinishPacketClientSelectedTeamBuffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<packets::PacketClientSelectedTeam> root) { fbb.Finish(root); }

}  // namespace packets

#endif  // FLATBUFFERS_GENERATED_PACKETCLIENTSELECTEDTEAM_PACKETS_H_
